### ISSUE TITLE
Check for file that exist in git folder is not accurable

### ISSUE THREAD

**Issue by mars90226** [APZelos/blamer.nvim#10]
The check for file that exist in git folder is not accurable (`s:IsFileInPath`). 
The following step will cause blamer.nvim to mess up setting:

1. Create a git repo in home folder, for example `/home/mars/test`.
2. `cd` to `/home/mars/test`.
3. `nvim term:///home/mars/test//8888:/bin/bash` will open a terminal buffer in `/home/mars/test`.
4. The cursor will be messed up by blamer.nvim.

`s:IsFileInPath` should check if file is actually inside path, not only match path.

**Comment by georgesofianosgr** [comment]
Is this still valid with the latest changes of master branch  ?

**Comment by mars90226** [comment]
Sorry for the slow reply, the problem is gone in latest commit of master branch. Thanks!
