### ISSUE TITLE
Check for git repo along the path the file comes from

### ISSUE THREAD

**Issue by simonweil** [APZelos/blamer.nvim#15]
Assume that there is a git repo at the path: /home/user/project

Do the following steps:
- cd /
- nvim /home/user/project/file.vim

Expected result: the git repo is recognized and blamming is working

Actual result: A message says: "[blamer.nvim] Not a git repository"

Thanks for an awesome plugin!

**Comment by bs** [comment]
Just came here to check on exactly this. Thanks for your work!
