### ISSUE TITLE
[Feature request] Show only in active split

### ISSUE THREAD

**Issue by CallumHoward** [APZelos/blamer.nvim#18]
It would be really nice to have an option to only show the git blame in the current active split. This is for the scenario when editing the same file in two seperate splits.

**Comment by georgesofianosgr** [comment]
This is partially fixed on the latest refactor which will be merged soon. When you leave a split the message is get hidden. Unfortunately I don't think is possible to hide the message for the same buffer in split because the virtual text is being set on the buffer itself.

**Comment by CallumHoward** [comment]
Thanks for all your hard work, looking forward to that new release!
