### ISSUE TITLE
Pre-existing virtual text is lost after blamer run on the same line

### ISSUE THREAD

**Issue by APZelos** [APZelos/blamer.nvim#2]

**Comment by simonweil** [comment]
This is a little bugging... Any chance to do something about it?
Thanks for this cool plugin :)

**Comment by APZelos** [comment]
Thank you very much 😄 

I have yet to found an easy way around this. I don't know if neovim supports a way of showing a virtual text without overwriting others on the same line

**Comment by simonweil** [comment]
I assume that not, maybe the neovim team have good suggestions how to deal with such a situation.

**Comment by gmcz** [comment]
What about an option to put the text in the status line instead of as virtual text at the end of the current line?
