### ISSUE TITLE
[blamer.nvim] fatal: file home/views.py has only 63 lines

### ISSUE THREAD

**Issue by aasutossh** [APZelos/blamer.nvim#20]
The error keeps echoing from time to time.

The plugin is working perfectly, I just wanted to notify you if it is something that needs to be solved or not.

**Comment by dimtion** [comment]
Very nice plugin!

I have the issue, It happens when I scroll past the end of the last saved file. To overcome that I need to save the file again `:wq`.

**Comment by drn** [comment]
https://github.com/APZelos/blamer.nvim/pull/16 resolves this issue and is pending review

**Comment by georgesofianosgr** [comment]
Pull request #16 accepted.
