### ISSUE TITLE
Feature Request: Auto hide in insert mode

### ISSUE THREAD

**Issue by zYeoman** [APZelos/blamer.nvim#27]
A workaround
```vim
autocmd InsertEnter * :BlamerHide
autocmd InsertLeave * :BlamerShow
```

but I think it should store the status before InsertEnter and load  previous status after InsertLeave.

And I suggest 
```vim
  autocmd BufLeave,InsertEnter * :BlamerHide
  autocmd BufEnter,InsertLeave * :BlamerShow
```

**Comment by CallumHoward** [comment]
Came to request the same thing.

**Comment by pirey** [comment]
+1 for this feature request.

Since there is an [option to hide on visual mode](https://github.com/APZelos/blamer.nvim/commit/09d8673e7cdca65ce654a9b8deb84b587d002220), 
an option for insert mode is make sense, no?

**Comment by CallumHoward** [comment]
Thanks! 🙏
