### ISSUE TITLE
Selecting multiple lines slows down pretty hard

### ISSUE THREAD

**Issue by WhyNotHugo** [APZelos/blamer.nvim#32]
When entering visual mode, as I select more lines nvim slows down **a lot**. With 10-20 lines there's almost a second of lag, but with ~100 lines selected, nvim grinds to a halt taking several seconds to respond to any movement.

My impression is that the problem is because each line is fetched from `git` individually, and this just piles up hundreds of calls to `git`.

I'm no expert here, but I _do_ think that some of these approaches might help:

- Cache git blame while the file does not change.
- Get all `blame` data for the entire file at once and parse that internally.
- Auto-disable when selecting more than `n` lines (`n` can be either hardcoded or configurable?).

**Comment by sensorario** [comment]
Same problem here!

**Comment by WhyNotHugo** [comment]
I turned blamer off for visual mode. I don't really need it in visual mode anyway, and it gets rid of the slowness:

```lua
-- In visual mode it's visually annoying AND slows down Vim A LOT.
vim.g.blamer_show_in_visual_modes = 0
```

**Comment by kafelix496** [comment]
I think 'Auto-disable when selecting more than n lines (n can be either hardcoded or configurable?).' would be really helpful.

**Comment by WhyNotHugo** [comment]
That's pretty much what `blamer_show_in_visual_modes` does, but for `n==1`.
