### ISSUE TITLE
Blamer is covered by indentlines

### ISSUE THREAD

**Issue by WhyNotHugo** [APZelos/blamer.nvim#38]
I use https://github.com/lukas-reineke/indent-blankline.nvim

It draws indentation lines and does this by drawing virtual text in empty lines.

Blamer positions itself on the left, so is expects to use the same position as  the other plug-in. They overlap and the other win gets rendered.

Is there any way I can make blamer draw aligned with respect to existing virtual text?

Or should indentlines be doing something different?

**Comment by APZelos** [comment]
Hello, could you provide a screenshot to display exactly what's going on?

**Comment by WhyNotHugo** [comment]
Sorry, debugging this further it turns out the issue was elsewhere -- blamer was actually not rendering and the blame lines were rendered by something else, which was buggy.

Sorry for the noise :sweat_smile:
