### ISSUE TITLE
Can't enable blamer when g:blamer_enabled initially set to 0

### ISSUE THREAD

**Issue by hillaryychan** [APZelos/blamer.nvim#41]
Steps to reproduce:

1. Have `let g:blamer_enabled = 0` in your `.vimrc` or `init.vim`
2. Open tracked file in a git repo
3. Call `:BlamerShow` or `:BlamerToggle`

**Comment by georgesofianosgr** [comment]
Thanks for opening an issue, I noticed that too yesterday. I will try to fix it this week

**Comment by hillaryychan** [comment]
Thanks for the reply.

I ended up looking into this and made a PR before I saw your comment. Feel free to dismiss my changes and fix it as you please.

**Comment by woxiqingxian** [comment]
Expect to fix the problem
